server:
  port: 8081

spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/books_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:admin}
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000
      driver-class-name: org.postgresql.Driver

app:
  cache:
    cacheType: redis
    cache-names:
      - DATABASE_BOOKS_BY_TITLE_AND_AUTHOR
      - DATABASE_BOOKS_BY_CATEGORY_NAME
    caches:
      DATABASE_BOOKS_BY_TITLE_AND_AUTHOR:
        expiry: 10m
      DATABASE_BOOKS_BY_CATEGORY_NAME:
        expiry: 10m
